SET DEFINE OFF;
Insert into MSSUBBRANCH
   (BRANCHCODE, SUBBRANCHCODE, SUBBRANCHNAMEENG, SUBBRANCHNAMENEP, PHONENO, SUBBRANCADD, SUBBRANCNEPADD)
 Values
   ('01', 1, 'Head Office', 'k|dÚv ZFFvF', '462536526', 'Hattisar', 'xflQ;f/');
Insert into MSSUBBRANCH
   (BRANCHCODE, SUBBRANCHCODE, SUBBRANCHNAMEENG, SUBBRANCHNAMENEP, PHONENO, SUBBRANCADD, SUBBRANCNEPADD)
 Values
   ('02', 3, 'Birgunj Office', 'jL<u_h', '54241666', 'Birgunj', 'jL<u_h');
Insert into MSSUBBRANCH
   (BRANCHCODE, SUBBRANCHCODE, SUBBRANCHNAMEENG, SUBBRANCHNAMENEP, PHONENO, SUBBRANCADD, SUBBRANCNEPADD)
 Values
   ('02', 4, 'Bhojpur', 'ef]HkÚ/', '65214111', 'Bhojpur', 'ef]HkÚ/');
Insert into MSSUBBRANCH
   (BRANCHCODE, SUBBRANCHCODE, SUBBRANCHNAMEENG, SUBBRANCHNAMENEP, PHONENO, SUBBRANCADD, SUBBRANCNEPADD)
 Values
   ('01', 2, 'Newroad', 'GoÚ/f]*', '41425415', 'Newroad', 'GoÚ/f]*');
COMMIT;
